# Generated by Django 2.2.4 on 2020-06-03 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(blank=True, max_length=25)),
                ('definition_1', models.CharField(blank=True, max_length=250)),
                ('definition_2', models.CharField(blank=True, max_length=250)),
                ('definition_3', models.CharField(blank=True, max_length=250)),
                ('definition_4', models.CharField(blank=True, max_length=250)),
                ('definition_5', models.CharField(blank=True, max_length=250)),
                ('alternate_spellings', models.CharField(blank=True, max_length=50)),
                ('case', models.CharField(blank=True, choices=[('', ''), ('nom.', 'nominative'), ('acc.', 'accusative'), ('gen.', 'genitive'), ('dat.', 'dative')], default='', max_length=5)),
                ('gender', models.CharField(blank=True, choices=[('', ''), ('m.', 'masculine'), ('f.', 'feminine'), ('n.', 'neuter')], default='', max_length=2)),
            ],
            options={
                'ordering': ['word'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(blank=True, max_length=3)),
                ('history', models.CharField(blank=True, max_length=2000)),
                ('frequency', models.CharField(blank=True, max_length=3)),
                ('compounds', models.CharField(blank=True, max_length=500)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordhoard.Word')),
            ],
            options={
                'ordering': ['group'],
            },
        ),
    ]
